#!/bin/bash

echo -e "\e[40;38;5;82mSSH port degistirme islemi basliyor...\e[0m"
echo -e "\e[40;38;5;82m...\e[0m"
read -p $'\e[1;44mSSH Portu Ne Olsun? (Varsayilan icin Enter: 2210)\e[0m: ' sshportu
if [ -z "$sshportu" ]; then
  sshportu='2210'
fi

# İşletim sistemi belirleme
os_name=$(grep "^NAME" /etc/os-release | awk -F= '{print $2}' | tr -d '"')

# İşletim sistemini ekrana yazdır
echo -e "\e[40;38;5;82mTespit edilen işletim sistemi: $os_name\e[0m"

# Mevcut SSH portunu bul ve degistir
current_port=$(grep "^Port " /etc/ssh/sshd_config | awk '{print $2}')
if [ -z "$current_port" ]; then
  current_port=22
fi

# SSHD yapılandırma dosyasındaki portu değiştir
sed -i "s/^Port $current_port/Port $sshportu/g" /etc/ssh/sshd_config

# CentOS/AlmaLinux için işlemler
if [[ "$os_name" == "CentOS Linux" || "$os_name" == "AlmaLinux" ]]; then
  # Gerekli policycoreutils paketlerini yükle
  yum install -y policycoreutils-python policycoreutils-python-utils

  # SELinux ayarlarını güncelle
  if ! sudo semanage port -a -t ssh_port_t -p tcp $sshportu 2>/dev/null; then
    sudo semanage port -m -t ssh_port_t -p tcp $sshportu
  fi

  # Aktif zone'u bul ve firewall ayarlarını güncelle
  active_zones=$(firewall-cmd --get-active-zones | awk '{print $1}')
  for zone in $active_zones; do
    if ! firewall-cmd --permanent --zone=$zone --add-port=$sshportu/tcp 2>/dev/null; then
      echo "Port $sshportu zaten ekli veya başka bir hata oluştu."
    fi
  done

  # Firewall'ı yeniden yükle
  firewall-cmd --reload

# Ubuntu için işlemler
elif [[ "$os_name" == "Ubuntu" ]]; then
  # UFW kontrolü ve port ekleme
  if command -v ufw >/dev/null 2>&1; then
    if ! ufw allow $sshportu/tcp 2>/dev/null; then
      echo "Port $sshportu zaten ekli veya başka bir hata oluştu."
    fi
    ufw reload
  fi
fi

# SSHD servisini yeniden başlat
sudo systemctl restart sshd.service

# Yeni portu kontrol et ve ekrana yazdır
ss_output=$(ss -tlnp | grep ssh)
echo "$ss_output"

if echo "$ss_output" | grep -q ":$sshportu "; then
  echo -e "\e[40;38;5;82mSSH Portu $sshportu olarak güncellendi. Terminali kapatip yeniden oturum açınız.  \e[0m"
  echo -e "\e[40;38;5;82mbye.\e[0m"
else
  echo -e "\e[41;97mBir terslik oldu, lütfen manuel olarak kontrol edin ve güncelleyin!\e[0m"
fi